//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.PL
{


    public partial class Itemusercontrol
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlcompch;
        protected global::System.Web.UI.WebControls.DropDownList ddlcateg;
        protected global::System.Web.UI.WebControls.DropDownList ddlunit;
        protected global::System.Web.UI.WebControls.FileUpload File1;
        protected global::System.Web.UI.WebControls.Label Label11;
        protected global::System.Web.UI.WebControls.Image Imageprod;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpid;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpdname;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpdqty;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpdprice;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpdbarcode;
        protected global::System.Web.UI.WebControls.TextBox TextBoxpdcost;
        protected global::System.Web.UI.WebControls.Label Label9;
        protected global::System.Web.UI.WebControls.Label Label10;   



        
    }
}
